### ISSUE TITLE
Decide on a project name

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/2022#1]
What should we call ourselves? It should probably capture the directed evolution theme rather than the lactose production one? But that's just my take on it!

**Comment by m-a-young** [comment]
Probably all lean a little too heavily on the lactose side of things:
Evolutio-dairy
Biolo-cheese
Cheddar-ected

Maybe a little better:
Homeostasisstance
Mutagenhance
Virassistance (if using phages?)

**Comment by connietreanor** [comment]
BacLac

**Comment by TheLostLambda** [comment]
https://docs.google.com/document/d/1Nwd9wyi_yeq-gQci4uUW8d3TLbvyJU0iL4cx6vvYIPs/edit

**Comment by TaylorCWR** [comment]
Vivo La Evolution?!

**Comment by TheLostLambda** [comment]
Make a poll about this today!

**Comment by TheLostLambda** [comment]
We might have this sorted:

rEvolver – Vivo La Evolution
