### ISSUE TITLE
Start on a research document (Lactose Production)

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/2022#13]
Find it here: https://docs.google.com/document/d/1jNjFIIeP9VeA7Frx8VI5Y0R48bYgmIpABJucOEWEzEk/edit?usp=sharing

**Comment by TaylorCWR** [comment]
Alex emailed Dr. Alvey asking for information or issues we haven't thought of yet :)

**Comment by alxconnolly** [comment]
From meeting with Tuck: We'll be working with bacterial directed evolution so the Neisseria meniningitidisβ1–4 Galactosyl Transferase (NmLgtB) seems the most promising so far. Challenge will be getting this to make **only** lactose, as opposed to the other eight galactoside derivatives that NmLgtB was reported to make.

**Comment by TheLostLambda** [comment]
Also look into just recombinantly expressing the mammalian enzymes in bacteria — would be good to confirm if they do or don't work in bacteria!

**Comment by TheLostLambda** [comment]
Calling this "started" as well — still needs work, but that's captured by a number of other new tasks
