### ISSUE TITLE
Survey- synzeug tools desired by other iGEM teams

### ISSUE THREAD

**Issue by alxconnolly** [Sheffield-iGE/2022#22]

**Comment by alxconnolly** [comment]
https://docs.google.com/document/d/1CgkfjS9oTzHFxLv6IQwDXg1v6BZfSupBdXU37FrQWzk/edit

Not really feeling this task (just cause I'd rather prioritise the genetic circuit stuff atm). Would be great if anyone wants to take this on, make it into a Google Forms survey, circulate via Taylor/someone with insta/twitter access to the other iGEM teams.

**Comment by TaylorCWR** [comment]
Sent off! :)
