### ISSUE TITLE
IDT sponsorship application

### ISSUE THREAD

**Issue by TaylorCWR** [Sheffield-iGE/2022#26]
https://forms.office.com/Pages/ResponsePage.aspx?id=R5wcdyR_3ESVjjT4cTqDlMjwxSiKn0ZFstlsgs5EmZ5UMUFTQkI3UVdHUE5UQjlPTzVHVVVBTzdIQy4u

**Comment by TheLostLambda** [comment]
I've submitted the form to IDT, but I'm not sure where we go from here!

**Comment by TheLostLambda** [comment]
Jk, lol, we need to wait two weeks to hear back from people!

**Comment by TheLostLambda** [comment]
[Print - IDT iGEM Ordering Credentials.pdf](https://github.com/Sheffield-iGE/2022/files/8975628/Print.-.IDT.iGEM.Ordering.Credentials.pdf)
