### ISSUE TITLE
Baseline EC, VN growth curves for wc 27/06/2022

### ISSUE THREAD

**Issue by TaylorCWR** [Sheffield-iGE/2022#29]
Creating media, genome seq strains (expensive though), plus some more pondering :)

**Comment by TaylorCWR** [comment]
Brooks will look at growth slowing genes today - good luck sir

**Comment by TaylorCWR** [comment]
Characterise growth for NEXT WEEK :)

**Comment by TaylorCWR** [comment]
Growth curves of E. coli (WT - Dh5a or BL21 (protein-expressing strain)) for next week.

**Comment by TheLostLambda** [comment]
https://benchling.com/s/prt-mb8jU4IxqoGTEAdbAXHG?m=slm-Q7yK9a4EE9lM5PbiLHlh
