### ISSUE TITLE
Write a big "Minutes" document or use the Mainboard more frequently

### ISSUE THREAD

**Issue by TaylorCWR** [Sheffield-iGE/2022#48]

**Comment by alxconnolly** [comment]
Reckon we can combine this with the 'The Plan' document? i.e. we'd add the minutes to the bottom each morning meeting but we'd still have the overall plan at the beginning to keep us focused on the end goal.

**Comment by alxconnolly** [comment]
So the mainboard is still useful for keeping a record of how each task progresses, and stops us from forgetting about low priority tasks, but we'd also have a chronological written record of what everyone is working on each day. idk if that makes sense but I do think we can use both without repeating ourselves

**Comment by TheLostLambda** [comment]
I'd be down for that! Would help us keep the big picture in mind too!

**Comment by TheLostLambda** [comment]
Alex has started adding notes to the plan document — we should try our best to keep this up!
