### ISSUE TITLE
Contact Tuck + Arrange a meeting about project

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/2022#7]

**Comment by TaylorCWR** [comment]
Wednesday 1-2pm - Engineering heartspace

**Comment by TaylorCWR** [comment]
Come up with Q for Tuck today
-common barriers for d. evo
-etc.

**Comment by TaylorCWR** [comment]
https://docs.google.com/document/d/1KDKhySISrkm0dH80Ir1M_is0jCreNCYSDly4VWBKjBY/edit
