### ISSUE TITLE
Figure out how / where to do DNA sequencing in house

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/2022#9]
Do we have nanopores around?

**Comment by Dedude007** [comment]
Sent Matt Wyles an email, Hopefully he'll respond soon with prices ect.

**Comment by TheLostLambda** [comment]
Hi Dylan,

Thanks for getting in touch. Yes, I'd be happy to run some samples on the ONT GridION for you. It is ~ £500 per flowcell, plus a cost for library prep, which will depend on prep method, level of multiplexing, etc. If you have a uni account (starting X/ or R/) then we can process any payments as an internal transfer (no VAT added). I'm afraid we don't work with Affymetrix microarrays in our lab - I believe they do at the Sitran lab. I'd be happy to have a chat about your project in more detail if you think we can help in any other way with the sample prep.

I actually made a poster last week for today's Biosciences symposium showcasing the equipment we have in the lab, but I'm stuck at home with covid so couldn't go! I attach it here - to give you an overview of what kit we have and methods we can support.

Thanks,
Helen

![Image](https://user-images.githubusercontent.com/6251883/175000918-56899349-ce10-4530-bbb9-1e7f7d920097.jpg)
